apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: wide-ep-llm-d-decode
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: DeepSeek-R1-0528
    llm-d.ai/role: decode
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    workerTemplate:
      metadata:
        labels:
          llm-d.ai/inferenceServing: "true"
          llm-d.ai/model: DeepSeek-R1-0528
          llm-d.ai/role: decode
      spec:
        serviceAccountName: deepseek-r1
        initContainers:
          - name: routing-proxy
            args:
              - --port=8000
              - --vllm-port=8200
              - --connector=nixlv2
              - -v=1
              - --secure-proxy=false
            image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.3.0
            imagePullPolicy: Always
            ports:
              - containerPort: 8000
            resources: {}
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 3Gi # 3Gi for NCCL 2.27 to be safe
        containers:
        - name: vllm-worker
          image: ghcr.io/llm-d/llm-d-cuda:v0.3.0
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RAWIO
            runAsGroup: 0
            runAsUser: 0
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
          args:
            - |-
              #################
              # RUN vLLM decode worker
              #################
              START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))
            
              # --data-parallel-hybrid-lb: Use exernal load balancing across nodes, and internal load balancing within a node
              # --enable-expert-parallel:  Use TPxDP in attention, EP in MoE layers
              # --async-scheduling: Reduce white space between engine steps
              # --enable-dbo:  Dual batch overlap (DBO) overlaps compute with collective communication.
              # --enable-eplb: Expert-parallel load balancing reduces EP load imbalance by replicating heavily-used experts Performance-memory tradeoff: on DeepSeekV3 eplb uses an extra 2GB per redundant expert per GPU Divisibility constraint: num_routed_experts (256 for DSv3) + num_redundant_experts must be divisible by the number of GPUs.

              # Create an environment variable for the vllm venv path so we can
              # override it for the GKE image as a temporary workaround.
              # TODO: Once we consolidate the images, we can just hard-code it.
              source ${VENV_PATH}/bin/activate
              exec vllm serve \
                deepseek-ai/DeepSeek-R1-0528 \
                --port 8200 \
                --trust-remote-code \
                --disable-uvicorn-access-log \
                --data-parallel-hybrid-lb \
                --enable-expert-parallel \
                --tensor-parallel-size $TP_SIZE \
                --data-parallel-size $((LWS_GROUP_SIZE * DP_SIZE_LOCAL)) \
                --data-parallel-size-local $DP_SIZE_LOCAL \
                --data-parallel-address ${LWS_LEADER_ADDRESS} \
                --data-parallel-rpc-port 5555 \
                --data-parallel-start-rank $START_RANK \
                --kv_transfer_config '{"kv_connector":"NixlConnector",
                                        "kv_role":"kv_both"}' \
                --async-scheduling \
                --enable-dbo \
                --dbo-decode-token-threshold 32 \
                --enable-eplb \
                --eplb-config '{"window_size":"1000",
                                "step_interval":"3000",
                                "num_redundant_experts":"32",
                                "log_balancedness":"False"}' \
                --compilation_config '{"cudagraph_mode": "FULL_DECODE_ONLY"}'
          env:
          # VLLM_MOE_DP_CHUNK_SIZE is a tunable parameter.
          # Higher values increase the memory footprint of the hidden states in the MoE layers,
          # which decreases the available memory for KV Cache.
          # Lower values may cause poor performance, especially in load-imbalanced scenarios.
          # The value 512 was chosen to be greater than the concurrency expected to see on any DP rank.
          # Has no effect when VLLM_ALL2ALL_BACKEND=deepep_high_throughput.
          - name: VLLM_MOE_DP_CHUNK_SIZE
            value: "512" # vLLM default is 256
          - name: DP_SIZE_LOCAL
            value: "8"
          - name: TP_SIZE
            value: "1"
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: VLLM_ALL2ALL_BACKEND
            value: deepep_low_latency
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: NVSHMEM_REMOTE_TRANSPORT
            value: ibgda
          - name: NVSHMEM_IB_ENABLE_IBGDA
            value: "true"
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: eth0
          - name: GLOO_SOCKET_IFNAME
            value: eth0
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: VLLM_LOGGING_LEVEL
            value: INFO
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
          - containerPort: 8200
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8200
          resources:
            limits:
              ephemeral-storage: 1Ti
              memory: 512Gi
              nvidia.com/gpu: "8"
            requests:
              cpu: 32
              ephemeral-storage: 1Ti
              memory: 512Gi
              nvidia.com/gpu: "8"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
