apiVersion: v1
kind: Pod
metadata:
  name: nixl-server-roce
  labels:
    app: nixl-server
  annotations:
    k8s.v1.cni.cncf.io/networks: multi-nic-network
spec:
  serviceAccountName: default
  containers:
  - name: nixl-server-roce
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
    image: quay.io/llm-d/llm-d-model-service-dev:latest
    imagePullPolicy: Always
    command: [
      '/bin/sh',
      '-c',
      'sleep infinity']
    env:
    - name: UCX_LOG_LEVEL
      value: "info"
    resources:
      requests:
        nvidia.com/gpu: 1
        cpu: "4"
        memory: 8Gi
        nvidia.com/roce_gdr: 2
      limits:
        nvidia.com/gpu: 1
        cpu: "4"
        memory: 8Gi
        nvidia.com/roce_gdr: 2
    volumeMounts:
      - name: dshm
        mountPath: "/dev/shm"
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
