apiVersion: v1
kind: ConfigMap
metadata:
  name: wide-ep-inference-gateway
  labels:
    app.kubernetes.io/gateway: wide-ep-inference-gateway
    app.kubernetes.io/component: inference-gateway
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            args:
              - proxy
              - router
              - --domain
              - $(POD_NAMESPACE).svc.cluster.local
              - --proxyLogLevel
              - warn
              - --proxyComponentLogLevel
              - misc:warn
              - --log_output_level
              - default:warn
            resources:
              limits:
                cpu: "8"
                memory: 16Gi
              requests:
                cpu: 2
                memory: 4Gi
  service: |
    spec:
      type: LoadBalancer
