apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker-model-runner-editor
rules:
  # Core API group resources
  - apiGroups: [""]
    resources:
      - pods
      - secrets
      - configmaps
      - services
      - endpoints
      - serviceaccounts
      - events
      - namespaces
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]

  # Workloads in the apps group
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Gateway API (Kubernetes Gateway)
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # RBAC debugging
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  # Monitoring
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - podmonitors
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker-model-runner-editor-binding
subjects:
  - kind: ServiceAccount
    name: docker-model-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docker-model-runner-editor
