apiVersion: v1
kind: Service
metadata:
  name: docker-model-runner
  labels:
    app: docker-model-runner
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: docker-model-runner
