inferenceExtension:
  replicas: 1
  image:
    name: vllm-k8s-inference-scheduler
    hub: ghcr.io/vllm-k8s
    tag: v0.3.2
    pullPolicy: Always
  extProcPort: 9002
  pluginsConfigFile: "pd-config.yaml"
  pluginsCustomConfig: # THIS CONFIG NEEDS TO BE CHECKED FOR INF SCHEDULER NEW IMAGE
    pd-config.yaml: |
      # ALWAYS DO PD IN THIS EXAMPLE (THRESHOLD 0)
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      plugins:
      - type: prefill-header-handler
      - type: prefill-filter
      - type: decode-filter
      - type: max-score-picker
      - type: queue-scorer
        parameters:
          hashBlockSize: 5
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: pd-profile-handler
        parameters:
          threshold: 0
          hashBlockSize: 5
      schedulingProfiles:
      - name: prefill
        plugins:
        - pluginRef: prefill-filter
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker
      - name: decode
        plugins:
        - pluginRef: decode-filter
        - pluginRef: queue-scorer
          weight: 1.0
        - pluginRef: max-score-picker

  # Monitoring configuration for EPP
  monitoring:
    interval: "10s"
    # Service account token secret for authentication
    secret:
      name: pd-gateway-sa-metrics-reader-secret
    # Prometheus ServiceMonitor will be created when enabled for EPP metrics collection
    prometheus:
      enabled: true

inferencePool:
  apiVersion: inference.networking.x-k8s.io/v1alpha2 # use old API version for inference
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      vllm-k8s.ai/inferenceServing: "true"
      vllm-k8s.ai/model: ms-pd-vllm-k8s-modelservice
