# chart/templates/secrets.yaml
{{- if and .Values.secret.create .Values.secret.hfTokenValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "chart.secretKeyName" . }}: {{ .Values.secret.hfTokenValue | b64enc }}
{{- else if not .Values.secret.create }}
# Warning: Secret creation is disabled (secret.create=false).
# Ensure a secret named "{{ .Values.secret.name }}" with key "{{ include "chart.secretKeyName" . }}" exists in namespace "{{ .Release.Namespace | default .Values.namespace }}".
{{- else if not .Values.secret.hfTokenValue }}
# Warning: Secret creation is enabled (secret.create=true) but secret.hfTokenValue is empty.
# The secret "{{ .Values.secret.name }}" will not be created. Provide a value via --set secret.hfTokenValue=YOUR_TOKEN
{{- end }}