apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-model-runner.fullname" . }}
  labels:
    {{- include "docker-model-runner.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
