name: CI

on:
  push:
    branches:
      - master
    paths: ['.github/workflows/build.yml', '**/CMakeLists.txt', '**/*.hpp', '**/*.cpp']
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['.github/workflows/build.yml', '**/CMakeLists.txt', '**/*.hpp', '**/*.cpp']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  # group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}-${{ matrix.os }}-${{ matrix.type }}
  # cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [
          # macos-13,
          # macos-14,
          macos-latest,
          # ubuntu-22.04,
          ubuntu-latest,
          # windows-2019,
          # windows-latest,
        ]
        type: [
          Release,
          Debug,
        ]
    runs-on:  ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.type }} --parallel

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --test-dir tests --output-on-failure --verbose -C ${{ matrix.type }}
